name: parse-home

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.302" # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release --no-restore -o /home/runner/out ./src/MikanScan.ConsoleApp/MikanScan.ConsoleApp.csproj

      - name: Run
        env: # Or as an environment variable
          QBHOST: ${{ vars.QBHOST }}
          QBPASSWORD: ${{ vars.QBPASSWORD }}
          QBUSERNAME: ${{ vars.QBUSERNAME }}
          QBBASEDIR: ${{ vars.QBBASEDIR }}
          TELEGRAM:CHATID: ${{ vars.TELEGRAMCHATID }}
          TELEGRAM:TOKEN: ${{ vars.TELEGRAMTOKEN }}
          TELEGRAM:HOST: ${{ vars.TELEGRAMHOST }}
          RUNTYPE: 1
        run: | 
          [[ -e ./data/anime.db ]] && cp ./data/anime.db /home/runner/out/data/anime.db
          cd /home/runner/out
          dotnet MikanScan.ConsoleApp.dll      

      - name: Commit changes
        run: |
          pwd
          cp /home/runner/out/data/anime.db ./data/anime.db
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
  
          git add -A
          git commit -m "add more data"          
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
