name: parse-home

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.302" # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        env: # Or as an environment variable
          QBHOST: ${{ secrets.QBHOST }}
          QBPASSWORD: ${{ secrets.QBPASSWORD }}
          QBUSERNAME: ${{ secrets.QBUSERNAME }}
          QBBASEDIR: ${{ secrets.QBBASEDIR }}
          TELEGRAMCHATID: ${{ secrets.TELEGRAMCHATID }}
          TELEGRAMTOKEN: ${{ secrets.TELEGRAMTOKEN }}
          TELEGRAMHOST: ${{ vars.TELEGRAMHOST }}
        run: cd src/MikanScan.ConsoleApp && dotnet run -c Release --no-restore
      - shell: bash
        env:
          SUPER_SECRET: ${{ vars.TELEGRAMHOST }}
        run: |
          echo "$SUPER_SECRET"
