name: parse-home

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.302" # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: /home/runner/work/mikan-scan-action/mikan-scan-action/src/MikanScan.ConsoleApp/data/anime.db
          key: anime.db

      - name: Build
        env: # Or as an environment variable
          QBHOST: ${{ vars.QBHOST }}
          QBPASSWORD: ${{ vars.QBPASSWORD }}
          QBUSERNAME: ${{ vars.QBUSERNAME }}
          QBBASEDIR: ${{ vars.QBBASEDIR }}
          TELEGRAMCHATID: ${{ vars.TELEGRAMCHATID }}
          TELEGRAMTOKEN: ${{ vars.TELEGRAMTOKEN }}
          TELEGRAMHOST: ${{ vars.TELEGRAMHOST }}
        run: cd ./src/MikanScan.ConsoleApp && dotnet run -c Release --no-restore
      - shell: bash 
        env:
          SUPER_SECRET: ${{ vars.TELEGRAMHOST }}
        run: |
          echo "$SUPER_SECRET"
