name: parse-home

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.302" # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: restore cache
        uses: actions/cache/restore@v4
        id: cache-primes-restore
        with:
          path: /home/runner/out/anime.db
          key: anime.db

      - name: Build
        env: # Or as an environment variable
          QBHOST: ${{ vars.QBHOST }}
          QBPASSWORD: ${{ vars.QBPASSWORD }}
          QBUSERNAME: ${{ vars.QBUSERNAME }}
          QBBASEDIR: ${{ vars.QBBASEDIR }}
          TELEGRAMCHATID: ${{ vars.TELEGRAMCHATID }}
          TELEGRAMTOKEN: ${{ vars.TELEGRAMTOKEN }}
          TELEGRAMHOST: ${{ vars.TELEGRAMHOST }}
          RUNTYPE: 1
        run: cd ./src/MikanScan.ConsoleApp && dotnet publish -c Release --no-restore -o /home/runner/out && cd /home/runner/out && dotnet MikanScan.ConsoleApp.dll
      
      - name: save db cache
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: /home/runner/out/anime.db
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

      - uses: actions/upload-artifact@v4
        with:
          name: db-file
          path: /home/runner/out/anime.db
